# Site settings
title: IAP 2022 Activities
email: cjq@mit.edu
description: >-
  Lovingly scraped from the MIT events calendar.
baseurl: "/iap"

collections:
  events:
    output: false

# Build settings
theme: minima
plugins:
  - jekyll-feed
