# Site settings
title: IAP 2022 Activities
email: cjq@mit.edu
description: >-
  Lovingly scraped from the MIT events calendar.
baseurl: "/iap"

collections:
  events:
    output: false

defaults:
  - scope:
      type: categories
    values:
      layout: category_page
      permalink: :category/:item.html

# Build settings
theme: minima
plugins:
  - jekyll-feed
